# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = Admin.new(:email => "admin@example.com", :password => "adminadmin")
admin.save!

users = User.create!(
  [
    {email:'john_doe@example.com', name: 'john_doe', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user1.jpg"), filename:"sample-user1.jpg")},
    {email:'jane_smith@example.com', name: 'jane_smith', password: 'testpassword' ,image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user2.jpg"), filename:"sample-user2.jpg")},
    {email:'mike_jones@example.com', name: 'mike_jones', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user3.jpg"), filename:"sample-user3.jpg")},
    {email:'sara_kim@example.com', name: 'sara_kim', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user4.jpg"), filename:"sample-user4.jpg")},
    {email:'david_lee@example.com', name: 'david_lee', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user5.jpg"), filename:"sample-user5.jpg")},
    {email:'mary_smith@example.com', name: 'mary_smith', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user6.jpg"), filename:"sample-user6.jpg")},
    {email:'jason_kim@example.com', name: 'jason_kim', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user7.jpg"), filename:"sample-user7.jpg")},
    {email:'emily_wang@example.com', name: 'emily_wang', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user8.jpg"), filename:"sample-user8.jpg")},
    {email:'peter_nguyen@example.com', name: 'peter_nguyen', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user9.jpg"), filename:"sample-user9.jpg")},
    {email:'kevin_kang@example.com', name: 'kevin_kang', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user10.jpg"), filename:"sample-user10.jpg")},
    {email:'stephanie_choi@example.com', name: 'stephanie_choi', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user11.jpg"), filename:"sample-user11.jpg")},
    {email:'jennifer_park@example.com', name: 'jennifer_park', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user12.jpg"), filename:"sample-user12.jpg")},
    {email:'joshua_lee@example.com', name: 'joshua_lee', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user13.jpg"), filename:"sample-user13.jpg")},
    {email:'kristen_kim@example.com', name: 'kristen_kim', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user14.jpg"), filename:"sample-user14.jpg")},
    {email:'benjamin_wong@example.com', name: 'benjamin_wong', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user15.jpg"), filename:"sample-user15.jpg")},
    {email:'rachel_kim@example.com', name: 'rachel_kim', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user16.jpg"), filename:"sample-user16.jpg")},
    {email:'andrew_lee@example.com', name: 'andrew_lee', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user17.jpg"), filename:"sample-user17.jpg")},
    {email:'lisa_wang@example.com', name: 'lisa_wang', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user18.jpg"), filename:"sample-user18.jpg")},
    {email:'samuel_kim@example.com', name: 'samuel_kim', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user19.jpg"), filename:"sample-user19.jpg")},
    {email:'julia_choi@example.com', name: 'julia_choi', password: 'testpassword', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user20.jpg"), filename:"sample-user20.jpg")}
  ]
)

production_areas = ProductionArea.create!(
  [
    {name: 'ブレンド'},
    {name: 'ブラジル'},
    {name: 'コロンビア'},
    {name: 'エチオピア'},
    {name: 'グアテマラ'},
    {name: 'コスタリカ'},
    {name: 'ケニア'},
    {name: 'その他'}
  ]
)

recipes = Recipe.create!(
  [
    {production_area_id: 6, user_id: 11, name: 'コロンビア', coffee_beans_name: 'コスタリカコロンビア', roast: 1, amount: 30, grind: 0, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'コーノMD', paper: '純正', point: '甘みと酸味のバランスが良く、後味に苦みが感じられます。スッキリとした味わいを楽しめます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe1.jpg"), filename:"sample-recipe1.jpg")},
    {production_area_id: 7, user_id: 4, name: 'ケニアAA', coffee_beans_name: 'スターバックス ケニアAA', roast: 2, amount: 25, grind: 4, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '酸味が前面に出た味わいで、フルーティーな香りがします。グラインダーの設定に注意してください。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe2.jpg"), filename:"sample-recipe2.jpg")},
    {production_area_id: 2, user_id: 3, name: 'ブラジル', coffee_beans_name: 'キリン珈琲 ブラジル', roast: 0, amount: 18, grind: 1, temperature: 83, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: 'コクがあって、深い味わいです。ウェーブで抽出することで、豊かな香りを引き出します。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe3.jpg"), filename:"sample-recipe3.jpg")},
    {production_area_id: 1, user_id: 12, name: 'モカジャバ', coffee_beans_name: 'キリン珈琲 モカジャバ', roast: 2, amount: 30, grind: 3, temperature: 89, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'V60', paper: '純正', point: '甘くフルーティーな香りがあり、苦みが少なめです。グラインドの細かさに注意してください。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe4.jpg"), filename:"sample-recipe4.jpg")},
    {production_area_id: 5, user_id: 10, name: 'グアテマラ', coffee_beans_name: 'ドトールコーヒー グアテマラ', roast: 1, amount: 20, grind: 0, temperature: 84, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'カリタ3つ穴', paper: '純正', point: 'すっきりとした口当たりで、フルーティーな香りがします。豆を細かく挽いて抽出すると、風味が増します。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe5.jpg"), filename:"sample-recipe5.jpg")},
    {production_area_id: 7, user_id: 8, name: 'ケニアAA', coffee_beans_name: 'スターバックス ケニアAA', roast: 2, amount: 28, grind: 4, temperature: 86, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '香りが高く、フルーティーな味わいが特徴です。苦味と酸味がバランス良く、飲みやすい一杯に仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe6.jpg"), filename:"sample-recipe6.jpg")},
    {production_area_id: 5, user_id: 18, name: 'グァテマラアンティグア', coffee_beans_name: 'ベローナ グァテマラアンティグア', roast: 0, amount: 32, grind: 3, temperature: 90, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: '豊かなコクと甘みがあり、酸味は控えめです。やや濃厚な味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe7.jpg"), filename:"sample-recipe7.jpg")},
    {production_area_id: 8, user_id: 5, name: 'ジャマイカブルーマウンテン', coffee_beans_name: 'アンジェラス コーヒー ジャマイカブルーマウンテン', roast: 1, amount: 25, grind: 1, temperature: 84, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'コーノMD', paper: '純正', point: 'フルーティーな香りと酸味があり、味わいはやや軽めです。苦味は控えめで、飲みやすい一杯に仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe8.jpg"), filename:"sample-recipe8.jpg")},
    {production_area_id: 6, user_id: 9, name: 'コロンビア・スプレモ', coffee_beans_name: 'ブルーボトル コロンビア・スプレモ', roast: 2, amount: 25, grind: 3, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: 'コクがあり、苦味も適度にあります。フルーティーな味わいが特徴です。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe9.jpg"), filename:"sample-recipe9.jpg")},
    {production_area_id: 6, user_id: 14, name: 'コスタリカ・モンテヴェルデ', coffee_beans_name: 'モノトリ COFFEE MAKERS コスタリカ・モンテヴェルデ', roast: 1, amount: 18, grind: 4, temperature: 80, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: '軽やかでフルーティーな味わいです。コスタリカらしい優しい酸味が特徴です。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe10.jpg"), filename:"sample-recipe10.jpg")},
    {production_area_id: 2, user_id: 1, name: 'ブラジル・ミナスジェライス州', coffee_beans_name: 'キャロットコーヒー ブラジル ミナスジェライス', roast: 0, amount: 22, grind: 0, temperature: 92, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'コーノMD', paper: '純正', point: '濃厚でコクがあり、苦味が強めです。ブラジルコーヒーの味わいを堪能できます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe11.jpg"), filename:"sample-recipe11.jpg")},
    {production_area_id: 6, user_id: 9, name: 'コロンビアサンアグスティン', coffee_beans_name: 'キリマンジャロAA', roast: 2, amount: 30, grind: 4, temperature: 85, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'ウェーブ', paper: '純正', point: '豊かな風味と甘みがあり、酸味もしっかりと感じられる味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe12.jpg"), filename:"sample-recipe12.jpg")},
    {production_area_id: 8, user_id: 6, name: 'ブルーマウンテン', coffee_beans_name: 'ブルーマウンテン豆', roast: 1, amount: 25, grind: 3, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'カリタ3つ穴', paper: '純正', point: '深みのあるコクと、芳醇な香りが魅力的な味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe13.jpg"), filename:"sample-recipe13.jpg")},
    {production_area_id: 7, user_id: 17, name: 'ケニアAA', coffee_beans_name: 'ドトールケニアAA', roast: 2, amount: 25, grind: 3, temperature: 85, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: 'コクがあり、酸味が強く出ました。しっかりとした味わいに仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe14.jpg"), filename:"sample-recipe14.jpg")},
    {production_area_id: 5, user_id: 7, name: 'グァテマラアンティグア', coffee_beans_name: 'スターバックスグァテマラアンティグア', roast: 1, amount: 30, grind: 4, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'ウェーブ', paper: '純正', point: '爽やかでフルーティーな味わいに仕上がりました。酸味が強めですが、後味はすっきりしています。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe15.jpg"), filename:"sample-recipe15.jpg")},
    {production_area_id: 3, user_id: 10, name: 'コロンビアメデジン', coffee_beans_name: 'エクセルコーヒーコロンビアメデジン', roast: 0, amount: 20, grind: 1, temperature: 90, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'コーノMD', paper: '純正', point: '濃厚なコクと苦味があり、酸味は控えめです。しっかりとした味わいが楽しめます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe16.jpg"), filename:"sample-recipe16.jpg")},
    {production_area_id: 2, user_id: 3, name: 'ブラジルサントス', coffee_beans_name: 'タリーズブラジルサントス', roast: 1, amount: 35, grind: 0, temperature: 82, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'V60', paper: '純正', point: '酸味は控えめで、苦みが強めに出ました。コクもあり、深みのある味わいに仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe17.jpg"), filename:"sample-recipe17.jpg")},
    {production_area_id: 3, user_id: 7, name: 'コロンビア・エクセルソ', coffee_beans_name: 'ドトールコロンビア・エクセルソ', roast: 1, amount: 30, grind: 3, temperature: 82, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: 'フルーティーで甘みのある味わいに仕上げました。酸味も控えめで、飲みやすいコーヒーです。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe18.jpg"), filename:"sample-recipe18.jpg")},
    {production_area_id: 3, user_id: 9, name: 'コロンビアサンアグスティン', coffee_beans_name: 'スターバックス コロンビア サン アグスティン', roast: 2, amount: 25, grind: 4, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '酸味が程よく感じられ、甘みもある味わいに仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe19.jpg"), filename:"sample-recipe19.jpg")},
    {production_area_id: 2, user_id: 12, name: 'ブラジルイエローブルボン', coffee_beans_name: 'ドトールコーヒー ブラジルイエローブルボン', roast: 1, amount: 30, grind: 3, temperature: 83, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: '豆本来の風味が引き立ち、まろやかな味わいに仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe20.jpg"), filename:"sample-recipe20.jpg")},
    {production_area_id: 5, user_id: 7, name: 'グァテマラアンティグア', coffee_beans_name: 'スターバックスグァテマラアンティグア', roast: 2, amount: 25, grind: 3, temperature: 85, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '豊かな風味が楽しめます。やや苦味が強めですが、甘味も感じられるバランスの良い味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe21.jpg"), filename:"sample-recipe21.jpg")},
    {production_area_id: 2, user_id: 15, name: 'ブラジルシタイ', coffee_beans_name: 'ドトールコーヒーブラジルシタイ', roast: 0, amount: 30, grind: 1, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: '程よい酸味がある、まろやかでやわらかな味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe22.jpg"), filename:"sample-recipe22.jpg")},
    {production_area_id: 3, user_id: 11, name: 'コロンビアスプレモ', coffee_beans_name: 'エクセルシオールコロンビアスプレモ', roast: 1, amount: 20, grind: 4, temperature: 82, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'コーノMD', paper: '純正', point: '軽やかな口当たりで、フルーティな香りと甘味が際立つ味わいに仕上げました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe23.jpg"), filename:"sample-recipe23.jpg")},
    {production_area_id: 1, user_id: 8, name: 'ハイチブルーマウンテン', coffee_beans_name: 'UCCブルーマウンテンNo.1', roast: 2, amount: 25, grind: 3, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '芳醇な香りとコクがあり、すっきりとした後味です。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe24.jpg"), filename:"sample-recipe24.jpg")},
    {production_area_id: 5, user_id: 13, name: 'グァテマラアンティグア', coffee_beans_name: 'キリマンジャロAA', roast: 1, amount: 17, grind: 4, temperature: 82, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'ウェーブ', paper: '純正', point: '優しい酸味と程よい苦みがバランスよく、フルーティーな香りが感じられます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe25.jpg"), filename:"sample-recipe25.jpg")},
    {production_area_id: 2, user_id: 5, name: 'ブラジル産サントス', coffee_beans_name: 'ストアブランド', roast: 0, amount: 22, grind: 1, temperature: 91, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'コーノMD', paper: '純正', point: 'しっかりとした味わいで、苦味が強く、コクもしっかりと感じられます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe26.jpg"), filename:"sample-recipe26.jpg")},
    {production_area_id: 4, user_id: 10, name: 'モカエチオピア', coffee_beans_name: 'タリーズモカエチオピア', roast: 1, amount: 30, grind: 2, temperature: 90, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'V60', paper: '純正', point: '芳醇な香りと爽やかな酸味が特徴的で、コクもあります。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe27.jpg"), filename:"sample-recipe27.jpg")},
    {production_area_id: 7, user_id: 17, name: 'キリマンジャロ', coffee_beans_name: 'スターバックス キリマンジャロ', roast: 2, amount: 25, grind: 3, temperature: 88, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'カリタ3つ穴', paper: '純正', point: '風味豊かなフルーティーな味わいとなりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe28.jpg"), filename:"sample-recipe28.jpg")},
    {production_area_id: 5, user_id: 2, name: 'グァテマラ', coffee_beans_name: 'ミルクボーイズ グァテマラ', roast: 1, amount: 17, grind: 1, temperature: 84, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 180, dripper: 'ウェーブ', paper: '純正', point: 'フルーティーな酸味とコクのある味わいを楽しめます。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe29.jpg"), filename:"sample-recipe29.jpg")},
    {production_area_id: 8, user_id: 20, name: 'ブルーマウンテン', coffee_beans_name: 'タリーズ ブルーマウンテン', roast: 0, amount: 22, grind: 4, temperature: 92, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'コーノMD', paper: '純正', point: '甘い香りが広がる、優しい口当たりのコーヒーに仕上がりました。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe30.jpg"), filename:"sample-recipe30.jpg")},
    {production_area_id: 1, user_id: 7, name: 'モカ', coffee_beans_name: 'コメダ珈琲 モカ', roast: 2, amount: 30, grind: 0, temperature: 86, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'V60', paper: '純正', point: '酸味が効いたすっきりとした味わいです。', status: true, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe31.jpg"), filename:"sample-recipe31.jpg")},
    {production_area_id: 1, user_id: 19, name: 'ブルーマウンテン', coffee_beans_name: 'キリマンジャロブルーマウンテン', roast: 0, amount: 25, grind: 4, temperature: 85, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 210, dripper: 'ウェーブ', paper: '純正', point: '豊かな風味とコクを引き出すように抽出しました。飲み口はスムーズで、後味に苦味を感じます。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe32.jpg"), filename:"sample-recipe32.jpg")},
    {production_area_id: 8, user_id: 16, name: 'パナマゲイシャ', coffee_beans_name: 'スターバックスパナマゲイシャ', roast: 2, amount: 18, grind: 3, temperature: 87, total_pouring_amount: 300, extraction_amount: 270, total_extraction_time: 240, dripper: 'カリタ3つ穴', paper: '純正', point: '香りが高く、酸味が強めです。甘さも感じるので、全体的にバランスが良い味わいに仕上げました。', status: 'true', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-recipe33.jpg"), filename:"sample-recipe33.jpg")}
  ]
)



pouring_details = PouringDetail.create!(
  [
    {recipe_id: 1, start_at: 0, amount: 40, note: '豆を挽くときは、細かく挽いた方がより濃厚な味わいになります。'},
    {recipe_id: 1, start_at: 45, amount: 120 },
    {recipe_id: 1, start_at: 90, amount: 210 },
    {recipe_id: 1, start_at: 130, amount: 300 },
    {recipe_id: 1, start_at: 210, amount: 0, note: 'ミルクを加える場合は、あらかじめ加熱しておくとよりまろやかになります。'},
    {recipe_id: 2, start_at: 0, amount: 40, note: '一気にお湯を注がないように'},
    {recipe_id: 2, start_at: 45, amount: 120 },
    {recipe_id: 2, start_at: 90, amount: 210 },
    {recipe_id: 2, start_at: 130, amount: 300 },
    {recipe_id: 2, start_at: 210, amount: 0, note: '落とし切る'},
    {recipe_id: 3, start_at: 0, amount: 40, note: 'コーヒー豆は、新鮮なものを使うとより美味しくいただけます。'},
    {recipe_id: 3, start_at: 45, amount: 120 },
    {recipe_id: 3, start_at: 90, amount: 210 },
    {recipe_id: 3, start_at: 130, amount: 300 },
    {recipe_id: 3, start_at: 210, amount: 0, note: 'クリームを加える場合は、よく泡立ててから加えるとよりきめ細かい口当たりになります。'},
    {recipe_id: 4, start_at: 0, amount: 40, note: 'コーヒー豆は、焙煎度合いによって味わいが変わるので、お好みで調整してください。'},
    {recipe_id: 4, start_at: 45, amount: 120 },
    {recipe_id: 4, start_at: 90, amount: 210 },
    {recipe_id: 4, start_at: 130, amount: 300 },
    {recipe_id: 4, start_at: 210, amount: 0, note: '甘味を加える場合は、はちみつや砂糖など、お好みのものを加えてください。'},
    {recipe_id: 5, start_at: 0, amount: 40, note: '湯の温度は約90℃が最適です。'},
    {recipe_id: 5, start_at: 45, amount: 120 },
    {recipe_id: 5, start_at: 90, amount: 210 },
    {recipe_id: 5, start_at: 130, amount: 300, note: 'ドリップ完了時には、豆の風味をしっかりと感じられるように抽出しましょう。' },
    {recipe_id: 5, start_at: 210, amount: 0, note: 'ドリップが終わったら、すぐにカップに注いでください。'},
    {recipe_id: 6, start_at: 0, amount: 40, note: '挽き方によっては、注ぐお湯の量を調整する必要があるかもしれません。'},
    {recipe_id: 6, start_at: 45, amount: 120 },
    {recipe_id: 6, start_at: 90, amount: 210, note: '抽出にかかる時間を調整することで、コーヒーの味わいが変わります。'},
    {recipe_id: 6, start_at: 130, amount: 300 },
    {recipe_id: 6, start_at: 210, amount: 0, note: 'カップの底にスプーンを置いて注ぐと、飛沫を防げます。'},
    {recipe_id: 7, start_at: 0, amount: 40, note: 'コーヒー豆は事前に挽いておくと、味わいが引き立ちます。'},
    {recipe_id: 7, start_at: 45, amount: 120 },
    {recipe_id: 7, start_at: 90, amount: 210, note: 'お湯の量や注ぎ方で、味わいを調整することができます。'},
    {recipe_id: 7, start_at: 130, amount: 300 },
    {recipe_id: 7, start_at: 210, amount: 0, note: '熱いお湯を注ぐときは、カップを温めると美味しさが増します。'},
    {recipe_id: 8, start_at: 0, amount: 20, note: '深煎りの豆を使うとよりコクが出ます。'},
    {recipe_id: 8, start_at: 40, amount: 120},
    {recipe_id: 8, start_at: 80, amount: 180},
    {recipe_id: 8, start_at: 130, amount: 250},
    {recipe_id: 8, start_at: 190, amount: 0, note: '美味しさの秘訣は、豆の鮮度とお湯の温度です。'},
    {recipe_id: 9, start_at: 0, amount: 30, note: '豆とお湯の量は、自分の好みに合わせて調整しましょう。'},
    {recipe_id: 9, start_at: 50, amount: 120},
    {recipe_id: 9, start_at: 90, amount: 200},
    {recipe_id: 9, start_at: 140, amount: 280},
    {recipe_id: 9, start_at: 210, amount: 0, note: '挽きたての豆を使うと、より香り高いコーヒーが楽しめます。'},
    {recipe_id: 10, start_at: 0, amount: 35, note: 'フレンチプレスで淹れる場合は、挽き目を粗くしてください。'},
    {recipe_id: 10, start_at: 40, amount: 120},
    {recipe_id: 10, start_at: 90, amount: 200},
    {recipe_id: 10, start_at: 140, amount: 280},
    {recipe_id: 10, start_at: 200, amount: 0, note: 'ミルで挽いた豆を使う場合は、水の温度に気をつけましょう。'},
    {recipe_id: 11, start_at: 0, amount: 25, note: '酸味が強いコーヒーが好きな場合は、挽き目を細かくしましょう。'},
    {recipe_id: 11, start_at: 40, amount: 120},
    {recipe_id: 11, start_at: 90, amount: 200},
    {recipe_id: 11, start_at: 140, amount: 280},
    {recipe_id: 11, start_at: 200, amount: 0, note: '豆の産地や焙煎度合いによって、味わいが異なります。'},
    {recipe_id: 12, start_at: 0, amount: 40, note: '最初は軽く湿らせる程度にお湯を注ぎます。'},
    {recipe_id: 12, start_at: 45, amount: 120},
    {recipe_id: 12, start_at: 90, amount: 210},
    {recipe_id: 12, start_at: 130, amount: 300},
    {recipe_id: 12, start_at: 210, amount: 0, note: '最後に、全体をかき混ぜながら湯気を飛ばします。'},
    {recipe_id: 13, start_at: 0, amount: 40, note: 'お湯は約90℃が適温です。'},
    {recipe_id: 13, start_at: 45, amount: 120},
    {recipe_id: 13, start_at: 90, amount: 210},
    {recipe_id: 13, start_at: 130, amount: 300},
    {recipe_id: 13, start_at: 210, amount: 0, note: '豆によっては、湯の温度や量を調整する必要があります。'},
    {recipe_id: 14, start_at: 0, amount: 30, note: '淹れたての豆を使用すると、より風味豊かになります。'},
    {recipe_id: 14, start_at: 30, amount: 100},
    {recipe_id: 14, start_at: 60, amount: 190},
    {recipe_id: 14, start_at: 120, amount: 280},
    {recipe_id: 14, start_at: 210, amount: 0, note: '美味しく淹れるポイントは、コーヒー豆とお湯の温度管理です。'},
    {recipe_id: 15, start_at: 0, amount: 35, note: 'お湯は沸騰させ過ぎず、湯量に対して均等にかけるように心がけます。'},
    {recipe_id: 15, start_at: 45, amount: 120},
    {recipe_id: 15, start_at: 90, amount: 200},
    {recipe_id: 15, start_at: 130, amount: 300},
    {recipe_id: 15, start_at: 210, amount: 0, note: 'グラインダーで挽く場合は、細かく挽かないように注意してください。'},
    {recipe_id: 16, start_at: 0, amount: 40, note: '挽きたての豆を使用すると、より風味豊かになります。'},
    {recipe_id: 16, start_at: 50, amount: 120},
    {recipe_id: 16, start_at: 90, amount: 200},
    {recipe_id: 16, start_at: 130, amount: 300},
    {recipe_id: 16, start_at: 210, amount: 0, note: '豆の種類や挽き具合によって、お湯の量や温度を微調整すると美味しく淹れられます。'},
    {recipe_id: 17, start_at: 0, amount: 45, note: '沸騰したお湯を使うと、苦味が強くなるので注意しましょう。'},
    {recipe_id: 17, start_at: 45, amount: 120},
    {recipe_id: 17, start_at: 90, amount: 200},
    {recipe_id: 17, start_at: 130, amount: 300},
    {recipe_id: 17, start_at: 210, amount: 0, note: '淹れ方によっては、粉っぽくなることがあるので、注意してください。'},
    {recipe_id: 18, start_at: 0, amount: 50, note: '粉末の豆は、お湯の注ぎ方に注意してください。'},
    {recipe_id: 18, start_at: 45, amount: 100},
    {recipe_id: 18, start_at: 90, amount: 200},
    {recipe_id: 18, start_at: 130, amount: 300, note: '淹れたてのコーヒーは香りが豊かです。'},
    {recipe_id: 18, start_at: 210, amount: 0, note: 'お湯の量は好みに応じて調整してください。'},
    {recipe_id: 19, start_at: 0, amount: 40, note: '一気にお湯を注がないように'},
    {recipe_id: 19, start_at: 45, amount: 120 },
    {recipe_id: 19, start_at: 90, amount: 210 },
    {recipe_id: 19, start_at: 130, amount: 300 },
    {recipe_id: 19, start_at: 210, amount: 0, note: '落とし切る' },
    {recipe_id: 20, start_at: 0, amount: 20},
    {recipe_id: 20, start_at: 30, amount: 80},
    {recipe_id: 20, start_at: 80, amount: 170, note: '湯量は多すぎないように'},
    {recipe_id: 20, start_at: 120, amount: 250},
    {recipe_id: 20, start_at: 190, amount: 0, note: 'しっかりと蒸らす'},
    {recipe_id: 21, start_at: 0, amount: 25},
    {recipe_id: 21, start_at: 35, amount: 90},
    {recipe_id: 21, start_at: 80, amount: 150, note: 'お湯を回しかけるように注ぐ'},
    {recipe_id: 21, start_at: 120, amount: 230},
    {recipe_id: 21, start_at: 200, amount: 0, note: 'ゆっくりと楽しむ'},
    {recipe_id: 22, start_at: 0, amount: 30},
    {recipe_id: 22, start_at: 40, amount: 100},
    {recipe_id: 22, start_at: 80, amount: 170, note: '煮詰めたような味わいになるように'},
    {recipe_id: 22, start_at: 120, amount: 240},
    {recipe_id: 22, start_at: 190, amount: 0, note: '風味が十分に引き出されたら完成'},
    {recipe_id: 23, start_at: 0, amount: 35},
    {recipe_id: 23, start_at: 50, amount: 110},
    {recipe_id: 23, start_at: 90, amount: 180, note: '湯量は少なめに'},
    {recipe_id: 23, start_at: 130, amount: 260},
    {recipe_id: 23, start_at: 210, amount: 0, note: 'スッキリとした味わいが特徴'},
    {recipe_id: 24, start_at: 0, amount: 50, note: '中火で淹れると良い香りが立ち上がります'},
    {recipe_id: 24, start_at: 45, amount: 150 },
    {recipe_id: 24, start_at: 90, amount: 250 },
    {recipe_id: 24, start_at: 130, amount: 350 },
    {recipe_id: 24, start_at: 210, amount: 0, note: '豆の種類によって淹れる時間は調整してください' },
    {recipe_id: 25, start_at: 0, amount: 40, note: '落ち着いた香りの深い味わいに仕上がります'},
    {recipe_id: 25, start_at: 45, amount: 120 },
    {recipe_id: 25, start_at: 90, amount: 210 },
    {recipe_id: 25, start_at: 130, amount: 300 },
    {recipe_id: 25, start_at: 210, amount: 0, note: '余熱で味わいが変わることがあるので、注いでからもう少し置くと良いです' },
    {recipe_id: 26, start_at: 0, amount: 30, note: '豆の挽き具合によって時間は調整してください'},
    {recipe_id: 26, start_at: 45, amount: 120 },
    {recipe_id: 26, start_at: 90, amount: 200 },
    {recipe_id: 26, start_at: 130, amount: 280 },
    {recipe_id: 26, start_at: 210, amount: 0, note: '湯量と温度で味わいが変わるので、調整してください' },
    {recipe_id: 27, start_at: 0, amount: 40, note: 'コクと酸味がある味わいに仕上がります'},
    {recipe_id: 27, start_at: 45, amount: 120 },
    {recipe_id: 27, start_at: 90, amount: 210 },
    {recipe_id: 27, start_at: 130, amount: 300 },
    {recipe_id: 27, start_at: 210, amount: 0, note: '挽き方によって湯量を調整してください' },
    {recipe_id: 28, start_at: 0, amount: 40, note: '味わい深く甘みがあるコーヒーに仕上がります'},
    {recipe_id: 28, start_at: 45, amount: 120 },
    {recipe_id: 28, start_at: 90, amount: 210 },
    {recipe_id: 28, start_at: 130, amount: 300 },
    {recipe_id: 28, start_at: 210, amount: 0, note: '時間をかけてゆっくり抽出することで味わいが変化します' },
    {recipe_id: 29, start_at: 0, amount: 40, note: '初めての方は注ぎ方に注意してください！'},
    {recipe_id: 29, start_at: 50, amount: 100 },
    {recipe_id: 29, start_at: 95, amount: 180, note: '注いでいる間に軽く混ぜてみてください'},
    {recipe_id: 29, start_at: 140, amount: 250 },
    {recipe_id: 29, start_at: 210, amount: 0, note: '楽しんでいただければ幸いです！'},
    {recipe_id: 30, start_at: 0, amount: 40, note: '最初はゆっくり注いで、徐々に速度を上げてください'},
    {recipe_id: 30, start_at: 45, amount: 120 },
    {recipe_id: 30, start_at: 90, amount: 210 },
    {recipe_id: 30, start_at: 130, amount: 300 },
    {recipe_id: 30, start_at: 210, amount: 0, note: '美味しいコーヒーをお楽しみください！'},
    {recipe_id: 31, start_at: 0, amount: 40, note: '粉を底に敷いてから注いでください。'},
    {recipe_id: 31, start_at: 45, amount: 120 },
    {recipe_id: 31, start_at: 90, amount: 210 },
    {recipe_id: 31, start_at: 130, amount: 300 },
    {recipe_id: 31, start_at: 210, amount: 0, note: '濃さが気に入ったら、次回は粉の量を増やしてみてください。'},
    {recipe_id: 32, start_at: 0, amount: 40, note: '最初は湯気が立ち上がるくらいの温度で注いでください'},
    {recipe_id: 32, start_at: 45, amount: 120 },
    {recipe_id: 32, start_at: 90, amount: 210 },
    {recipe_id: 32, start_at: 130, amount: 300 },
    {recipe_id: 32, start_at: 210, amount: 0, note: 'お好みの味に調整して楽しんでください！'},
    {recipe_id: 33, start_at: 0, amount: 30, note: '豆の挽き目は中挽きで調整してください'},
    {recipe_id: 33, start_at: 30, amount: 100 },
    {recipe_id: 33, start_at: 90, amount: 180, note: '湯量は蒸らし期間中は少な目にしてください'},
    {recipe_id: 33, start_at: 150, amount: 300 },
    {recipe_id: 33, start_at: 210, amount: 0, note: '丁寧に注いで、美味しく召し上がれ！'}
  ]
)

recipe_comments = RecipeComment.create!(
  [
    {comment: 'このレシピで淹れたコーヒーは美味しかったです！', user_id: 2, recipe_id: 11},
    {comment: '初めて挑戦しましたが、失敗せずに美味しいコーヒーができました！', user_id: 4, recipe_id: 26},
    {comment: 'グラインダーが壊れたので、挽いてもらうようにしてからこのレシピで淹れるようにしています。', user_id: 8, recipe_id: 14},
    {comment: '少し苦みが強かったので、豆の種類を変えたらより飲みやすくなりました。', user_id: 5, recipe_id: 5},
    {comment: 'このレシピはスッキリとしていて、飲みやすいコーヒーができました。', user_id: 3, recipe_id: 21},
    {comment: 'フレンチプレスで淹れるとコクがあって好きです。', user_id: 11, recipe_id: 19},
    {comment: '淹れ方に困っていたので助かりました！', user_id: 1, recipe_id: 1},
    {comment: 'このレシピをベースに自分なりにアレンジして淹れています。', user_id: 13, recipe_id: 7},
    {comment: '酸味がちょうどよく、好きな味わいでした。', user_id: 9, recipe_id: 17},
    {comment: '豆の挽き方が細かかったせいか、コーヒーが濁ってしまいました。', user_id: 7, recipe_id: 28},
    {comment: '水の温度にこだわっているので、自分なりに微調整しています。', user_id: 14, recipe_id: 31},
    {comment: 'このレシピで淹れたコーヒーは香り高く、とても美味しかったです。', user_id: 15, recipe_id: 2},
    {comment: '一度失敗してしまったけど、再チャレンジして美味しいコーヒーができました。', user_id: 17, recipe_id: 13},
    {comment: 'このレシピで淹れたコーヒーはコクがあって、ほんのり甘みも感じました。', user_id: 12, recipe_id: 6},
    {comment: '豆の種類によっては、このレシピでは少し苦すぎることもあるので注意が必要です。', user_id: 6, recipe_id: 23},
    {comment: 'このレシピで淹れたコーヒーは香りが良くて美味しかったです！', user_id: 8, recipe_id: 22},
    {comment: 'フレンチプレスで淹れると豆本来の風味が引き立ちますね。', user_id: 5, recipe_id: 15},
    {comment: 'このレシピで淹れたコーヒーは苦味が強かったので、牛乳を足して飲んでいます。', user_id: 13, recipe_id: 9},
    {comment: 'ブラックで飲んでも飲みやすく、美味しいです。', user_id: 2, recipe_id: 24},
    {comment: 'レシピ通りに淹れると、繊細な味わいのコーヒーができます。', user_id: 17, recipe_id: 2},
    {comment: '水の量が多いせいか、豆の風味が薄れてしまいました。', user_id: 4, recipe_id: 28},
    {comment: '豆の種類を変えたら、違う味わいのコーヒーができて楽しいです。', user_id: 9, recipe_id: 7},
    {comment: 'このレシピで淹れたコーヒーは、口当たりが滑らかでした。', user_id: 15, recipe_id: 21},
    {comment: '初心者でも簡単に淹れられるレシピだと思います。', user_id: 18, recipe_id: 31},
    {comment: '酸味が強めの豆でも、このレシピで淹れると美味しく飲めます。', user_id: 7, recipe_id: 26},
    {comment: 'このレシピを応用して、自分なりのオリジナルコーヒーを作っています。', user_id: 12, recipe_id: 11},
    {comment: 'コーヒーにまつわる様々な知識を学べるので、楽しいです。', user_id: 20, recipe_id: 33},
    {comment: '苦味が強すぎる場合は、豆の挽き方を変えるといいですね。', user_id: 1, recipe_id: 6},
    {comment: 'コーヒー淹れるのが苦手だったけど、このレシピを見てからは自信がつきました。', user_id: 14, recipe_id: 17},
    {comment: '美味しいレシピありがとうございます！', user_id: 3, recipe_id: 10},
    {comment: '苦味が少し強めでしたが、好みでした！', user_id: 5, recipe_id: 21},
    {comment: '簡単に作れました！', user_id: 7, recipe_id: 5},
    {comment: 'コクがあってとても美味しいです。', user_id: 2, recipe_id: 16},
    {comment: '香りがとても良く、癒されます。', user_id: 8, recipe_id: 24},
    {comment: '口当たりが滑らかで、飲みやすいです。', user_id: 11, recipe_id: 9},
    {comment: '甘めが好きなので、このレシピは私には合いませんでした。', user_id: 10, recipe_id: 13},
    {comment: '豆の種類によって味わいが異なるのが楽しいですね！', user_id: 6, recipe_id: 31},
    {comment: 'とてもクセになる味でした。', user_id: 13, recipe_id: 18},
    {comment: '豆の量を少し減らしてみたら、苦味が軽くなりました。', user_id: 17, recipe_id: 27},
    {comment: '朝の目覚めにぴったりの味わいです。', user_id: 14, recipe_id: 2},
    {comment: 'これからも作り続けたいレシピです！', user_id: 20, recipe_id: 7},
    {comment: '飲みやすくて、おいしかったです。', user_id: 4, recipe_id: 19},
    {comment: 'ミルを調整してみたら、味わいが変わりました。', user_id: 16, recipe_id: 28},
    {comment: '酸味が少し強めでしたが、美味しかったです。', user_id: 9, recipe_id: 22},
    {comment: '豆の挽き方が難しいですね。もう少し研究したいと思います。', user_id: 12, recipe_id: 11},
    {comment: 'このレシピを作ってから、コーヒーが好きになりました！', user_id: 18, recipe_id: 3},
    {comment: '淹れる前に豆を挽くのが面倒だったのですが、このレシピを知ってからは楽しい時間になりました。', user_id: 15, recipe_id: 26},
    {comment: 'このレシピはとても美味しいです。また作りたいと思います。', user_id: 7, recipe_id: 28},
    {comment: '苦味がしっかりしていて、コクもあるので好みの味でした。', user_id: 4, recipe_id: 17},
    {comment: 'ミルの調整が難しくて何度か失敗しましたが、最終的に美味しいコーヒーができました。', user_id: 14, recipe_id: 22},
    {comment: '香りがよく、飲みやすいです。', user_id: 5, recipe_id: 6},
    {comment: 'このレシピを知ってからは、毎朝コーヒーを楽しみにしています。', user_id: 8, recipe_id: 13},
    {comment: '豆の種類によって味わいが異なるのが楽しいですね。', user_id: 2, recipe_id: 31},
    {comment: '今までコーヒーは苦手でしたが、このレシピを知ってからは飲めるようになりました。', user_id: 10, recipe_id: 11},
    {comment: 'とても丁寧にレシピが書かれていて、作りやすかったです。', user_id: 6, recipe_id: 25},
    {comment: '美味しいコーヒーができてとても嬉しいです。', user_id: 12, recipe_id: 19},
    {comment: '口当たりが良く、まろやかな味わいでした。', user_id: 16, recipe_id: 1},
    {comment: 'このレシピを作ってみたら、普段よりも美味しいコーヒーができました。', user_id: 3, recipe_id: 9},
    {comment: '豆の挽き方と水の量のバランスが難しいですね。もっと練習したいと思います。', user_id: 18, recipe_id: 29},
    {comment: 'レシピ通りに作っても、豆の種類によって味が全然違うので楽しいです。', user_id: 11, recipe_id: 21},
    {comment: 'このレシピでコーヒーを淹れるのが楽しくて、毎日作っています。', user_id: 20, recipe_id: 16},
    {comment: '酸味と苦味のバランスが絶妙で、美味しかったです。', user_id: 1, recipe_id: 26},
    {comment: 'とても丁寧に作られたレシピでした。', user_id: 4, recipe_id: 29},
    {comment: '豆の選び方についても教えていただけると嬉しいです。', user_id: 9, recipe_id: 14},
    {comment: '苦味が少なく、飲みやすいです。', user_id: 15, recipe_id: 8},
    {comment: 'こだわりの豆で作ると、味が格別になりますね。', user_id: 17, recipe_id: 12},
    {comment: '甘みが強くて美味しかったです。', user_id: 2, recipe_id: 20},
    {comment: '豆の挽き方を工夫すると、味わいが変わるのが面白いです。', user_id: 19, recipe_id: 25},
    {comment: 'ホットでもアイスでも美味しくいただけます。', user_id: 8, recipe_id: 17},
    {comment: '味のバランスが取れていて、美味しいです。', user_id: 13, recipe_id: 30},
    {comment: 'これからもずっと愛されるレシピだと思います。', user_id: 5, recipe_id: 1},
    {comment: '香りがよくて、とても癒されました。', user_id: 16, recipe_id: 23},
    {comment: 'あまりコーヒーを飲まない人でも飲みやすい味です。', user_id: 14, recipe_id: 7},
    {comment: '豆の種類を変えてみると、全然違う味わいになりますね。', user_id: 1, recipe_id: 24},
    {comment: 'このレシピを知ってから、コーヒーの入ったマグカップを持つことが増えました。', user_id: 7, recipe_id: 21},
    {comment: '豆の挽き方や水の量を微調整すると、味わいの変化が分かって楽しいです。', user_id: 10, recipe_id: 31},
    {comment: 'クセが少なくて、飲みやすかったです。', user_id: 12, recipe_id: 16},
    {comment: '豆の品種によって、味わいの違いが分かりますね。', user_id: 20, recipe_id: 27},
    {comment: '苦味と甘みのバランスが絶妙でした。', user_id: 11, recipe_id: 22}
  ]
)

